### PR TITLE
Update pinned package versions, fixes #53

### LINKED ISSUE #53: docker-compose up fails
```
$ docker --version
Docker version 1.9.1, build a34a1d5
$ docker-compose up                                    
Building scan
Step 1 : FROM ubuntu:14.04.3
 ---> 6cc0fc2a5ee3
Step 2 : MAINTAINER V. David Zvenyach <vladlen.zvenyach@gsa.gov>
 ---> Using cache
 ---> 9c7124f58945
Step 3 : RUN apt-get update         -qq     && apt-get install         -qq         --yes         --no-install-recommends         --no-install-suggests       build-essential=11.6ubuntu6       curl=7.35.0-1ubuntu2.5       git=1:1.9.1-1ubuntu0.1       libc6-dev=2.19-0ubuntu6.6       libfontconfig1=2.11.0-0ubuntu4.1       libreadline-dev=6.3-4ubuntu2       libssl-dev=1.0.1f-1ubuntu2.15       libssl-doc=1.0.1f-1ubuntu2.15       libxml2-dev=2.9.1+dfsg1-3ubuntu4.4       libxslt1-dev=1.1.28-2build1       libyaml-dev=0.1.4-3ubuntu3.1       make=3.81-8.2ubuntu3       nodejs=0.10.25~dfsg2-2ubuntu1       npm=1.3.10~dfsg-1       python3-dev=3.4.0-0ubuntu2       python3-pip=1.5.4-1ubuntu3       unzip=6.0-9ubuntu1.3       wget=1.15-1ubuntu1.14.04.1       zlib1g-dev=1:1.2.8.dfsg-1ubuntu1       autoconf=2.69-6       automake=1:1.14.1-2ubuntu1       bison=2:3.0.2.dfsg-2       gawk=1:4.0.1+dfsg-2.1ubuntu2       libffi-dev=3.1~rc1+r3.0.13-12       libgdbm-dev=1.8.3-12build1       libncurses5-dev=5.9+20140118-1ubuntu1       libsqlite3-dev=3.8.2-1ubuntu2.1       libtool=2.4.2-1.7ubuntu1       pkg-config=0.26-1ubuntu4       sqlite3=3.8.2-1ubuntu2.1     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Running in eb3383000cf7
E: Version '7.35.0-1ubuntu2.5' for 'curl' was not found
E: Version '1:1.9.1-1ubuntu0.1' for 'git' was not found
E: Version '1.0.1f-1ubuntu2.15' for 'libssl-dev' was not found
E: Version '1.0.1f-1ubuntu2.15' for 'libssl-doc' was not found
E: Version '2.9.1+dfsg1-3ubuntu4.4' for 'libxml2-dev' was not found
E: Version '6.0-9ubuntu1.3' for 'unzip' was not found
ERROR: Service 'scan' failed to build: The command '/bin/sh -c apt-get update         -qq     && apt-get install         -qq         --yes         --no-install-recommends         --no-install-suggests       build-essential=11.6ubuntu6       curl=7.35.0-1ubuntu2.5       git=1:1.9.1-1ubuntu0.1       libc6-dev=2.19-0ubuntu6.6       libfontconfig1=2.11.0-0ubuntu4.1       libreadline-dev=6.3-4ubuntu2       libssl-dev=1.0.1f-1ubuntu2.15       libssl-doc=1.0.1f-1ubuntu2.15       libxml2-dev=2.9.1+dfsg1-3ubuntu4.4       libxslt1-dev=1.1.28-2build1       libyaml-dev=0.1.4-3ubuntu3.1       make=3.81-8.2ubuntu3       nodejs=0.10.25~dfsg2-2ubuntu1       npm=1.3.10~dfsg-1       python3-dev=3.4.0-0ubuntu2       python3-pip=1.5.4-1ubuntu3       unzip=6.0-9ubuntu1.3       wget=1.15-1ubuntu1.14.04.1       zlib1g-dev=1:1.2.8.dfsg-1ubuntu1       autoconf=2.69-6       automake=1:1.14.1-2ubuntu1       bison=2:3.0.2.dfsg-2       gawk=1:4.0.1+dfsg-2.1ubuntu2       libffi-dev=3.1~rc1+r3.0.13-12       libgdbm-dev=1.8.3-12build1       libncurses5-dev=5.9+20140118-1ubuntu1       libsqlite3-dev=3.8.2-1ubuntu2.1       libtool=2.4.2-1.7ubuntu1       pkg-config=0.26-1ubuntu4       sqlite3=3.8.2-1ubuntu2.1     && apt-get clean     && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

### PR DESCRIPTION
**Pull request by garrettr**

### CODE REVIEW

**Comment by ozzyjohnson** [comment]
Possibly worth relaxing these if we expect they're likely to fall off rapidly with a wildcard to allow for point releases.

`curl=7.35.0-1ubuntu2.*`

**Comment by konklone** [comment]
> `curl=7.35.0-1ubuntu2.*`

I didn't know that was possible! FWIW, I'm testing the current PR now, and if it works I'll merge to avoid @garrettr having to retest, since he fixed the underlying problem in #53.

Side note: Is it bad to see a `gpg: WARNING: This key is not certified with a trusted signature!` after importing a GPG key shortly before? Or does `GPG verified '/usr/local/rvm/archives/rvm-1.26.11.tgz'` afterwards indicate a separate command that proactively used the GPG key to verify the package?

image

**Comment by konklone** [comment]
This PR works just fine -- merging.

**Comment by garrettr** [comment]
> Is it bad to see a gpg: WARNING: This key is not certified with a trusted signature! after importing a GPG key shortly before?

@konklone It's not bad. It means that you are not leveraging the web of trust to verify with GPG, which is why GPG says "Good signature" but warns that the key is not certified with a trusted signature.

Depending on how you obtain the GPG key, this may or may not reduce the security of verification. For example, if you download the GPG key from an HTTPS website, then your security is reduced to that of HTTPS (you are theoretically vulnerable to a compromise of the server providing the key, or the usual litany of attacks against HTTPS). In this Dockerfile, you do better than that because you fetch the key from the keyservers by its full fingerprint, and `gpg --recv-keys` verifies that the downloaded key has the requested fingerprint (in recent versions of GPG).

There are two options to avoid this error message:

1. Generate a GPG key, use it to verify the keys of interest (out of band, web-of-trust style), and sign them. The signatures need to be attached to the key, so you could push them to the keyservers, or include the signed keys in your Git repo. You'll also need to include your GPG public key in this repo, and will need to import it (and set it to be ultimately trusted) before performing any other GPG actions.
2. As long as the source of the GPG keys is reasonably secure, you can tell GPG to implicitly trust all keys by passing `--trust-model always`.

I recommend option 2 as I think the benefits of option 1 are minimal and not worth the trouble.

**Comment by konklone** [comment]
> @konklone It's not bad. It means that you are not leveraging the web of trust to verify with GPG, which is why GPG says "Good signature" but warns that the key is not certified with a trusted signature.

Ahhhhh, yes, I used to know this. I agree that option 2 is the better way, especially since we're relying on HTTPS for loads of other things during the dependency building process. Thanks, @garrettr.

**Pull request merged**
