### PR TITLE
Docker tweaks

### PR DESCRIPTION
**Pull request by adelevie**
Two changes to get me up and running with Docker:

- Removed a hardcoded version of libc6-dev. Before, `docker-compose build` was breaking at this part. I know it's best practice to have these versions pinned down. But I don't know how to do that. I'll learn it and do it later.

- Use `/home/scanner` as a shared volume with the host. This allows the user to access the results of a scan in the host. Before, you could run scans, but the results were inaccessible, deep inside the container.

### CODE REVIEW

**Comment by afeld** [comment]
The changes look fine to me 👍

**Comment by adelevie** [comment]
Cool! How would I find the current version of `libc6-dev` so I can re-hardcode it in the Dockerfile?

**Comment by afeld** [comment]
Hmm, that does seem to be the latest version:

http://packages.ubuntu.com/trusty/libc6-dev

> `docker-compose build` was breaking at this part

What was the error?

**Comment by konklone** [comment]
cc @garrettr on this since I know he was having an issue with the second item this PR fixes.

**Comment by afeld** [comment]
Merging this now since it's broken, but feel free to send another PR to lock down the version if you like.

**Comment by garrettr** [comment]
@konklone Sorry, just getting back into working with this now. I can confirm that this PR fixes the issue I was having with retrieving scanner results from the container 👍.

**Pull request merged**
